[package]
name = "config"
version.workspace = true
edition.workspace = true

[dependencies]
actix-cors = { workspace = true }
actix-web = { workspace = true }
hbs = { workspace = true, features = ["dir_source"] }
tracing-subscriber = { workspace = true }